remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Kaan Borekci"
description: "Medical Devices · Robotics · ML for Healthcare"

# Turn off the default “View on GitHub” buttons
github:
  is_project_page: false

# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
#   - jekyll-remote-theme

# title: "Kaan Borekci"
# description: "Medical Devices · Robotics · ML for Healthcare"
